### ISSUE TITLE
[new-parser] Broken QueryTest#testRecursiveQueryWithBatchCommand

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5714]
## Parent issue
- #5678 

## Failing tests
- `org.drools.model.codegen.execmodel.QueryTest#testRecursiveQueryWithBatchCommand`

## Notes
- Both `STANDARD_FROM_DRL` and `PATTERN_DSL`.

## Rule code snippet
- Query.

## Error output
- The query result is empty. No parser error is visible in the output.

**Comment by tkobayas** [comment]
`/take`

**Comment by tkobayas** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/pull/5866
