### ISSUE TITLE
Is there any way to shorten the kbs rule loading time

### ISSUE THREAD

**Issue by repeatthink123yuchao** [apache/incubator-kie#5731]
We encountered a drools problem in our online environment and would like to ask for advice. The thing is like this,
We have approximately 160,000 rule files. When the project was started, the CompositeKnowledgeBuilder.build action was too time-consuming, causing the application to be unable to serve external users for a long time. Is there any way to shorten the kbs rule loading time?

drools version:7.74.1.Final

**Comment by repeatthink123yuchao** [comment]
heap	'package num'	'rule num of per package'	'rule counter'		load time(ms)	load time(min)
16g		8000			1							8000				212936			3.54
16g		8000			8							64000				667504			11.12
16g		8000			10							80000				756504			12.6
16g		8000			12							96000				1048131			17.46
16g		8000			14							112000				1156447			19.27
16g		8000			16							128000						
16g		8000			18							144000						
16g		8000			20							160000				1563920			26.065

**Comment by mariofusco** [comment]
That's cool because this is probably one of the biggest rules based installation of which I have ever heard. Regarding your question I have a few suggestions:

1. Are you using the executable model, i.e. rewriting the rules in pure Java at compile time? If not I strongly suggest to do so: it will make the compilation time a little longer but will pay back with a much faster startup at runtime.
2. Do all those rules actually belong to the knowledge base? Isn't it possible to shard them, based on the business logic of your application, and then split them in multiple KieBases, each with a more confined and better defined business scope?
3. If you have so many rules I bet that they are automatically generated in some way? If so can you please provide an example of those rules? Maybe we could find some common pattern allowing us to rewrite those rules in a more compact way and reduce their cardinality.

**Comment by repeatthink123yuchao** [comment]
Thank you very much for your reply. The details of the situation are as follows:

1 The current application only has 1 InternalKnowledgeBase
2. The system starts up and loads the drl file in the database. The database is read and the row records are written to the disk drl file. The contents of the file are as follows

directory /tmp/2024022219/rule_603_1_0_0_0.drl

package rule_603_1_0_0;
import java.util.*;
import static xxx.RuleUtils.*;

rule "rule_RD00000214"
    no-loop true
    lock-on-active true
    salience 11
    agenda-group "rule_603_1_0_0"
when
	$map : Map( RuleUtils.ruleEquals(rule_package_name,"rule_603_1_0_0"),equalsString(isExistListInRedis($map,"BLACK","[Org_no=documentNumber,P_subscribeLabel=subscribeLabel]&[License=documentNumber,P_subscribeLabel=subscribeLabel]"),"Y")
 	)

then
	 RuleUtils.assembleHitRuleCodes($map,"RD00000214");
	 RuleUtils.put($map,"RSE00000083_RGC00007454_setresult","pass");
RuleUtils.put($map,"M_ID_matched_flag","Y");

end


3 The project startup code is like this

    /**
     * Initialize rule component group
     */
    @PostConstruct
    public void concurrencyLoadInit() {
        String bn = "concurrency:policy rule initialization";
        Boolean result = Boolean.TRUE;
        StopWatch stopWatchForAll = StopWatch.createStarted();
        //group counter
        Integer groupNumberCounter = 0;
        //package counter
        Integer packageCounter = 0;
        //rule counter
        try {
            logger.info("{}:阶段:begin", bn);
            RuleKieBaseTool tempMap = new RuleKieBaseTool();
            StopWatch stopWatch = StopWatch.createStarted();
            //2.读取rule表配置信息 策略发布状态成功 + 规则组件状态上线成功 +规则已发布
            List<LprRulTabDTO> lprRulTabDTOList = rulTabMapper.selectByStatus(RuleEnum.RULE_RELEASE_SUCCESS.getCode());
            log.info("{}:阶段:策略规则初始化获取规则数据库配置完成 行记录数:{} 耗时:{}", bn, lprRulTabDTOList.size(), stopWatch.getTime());
            stopWatch.reset();
            stopWatch.start();

            //Map<package,List<rule>>
            Map<String, List<String>> ruleListMap = decodeRuleSetByTab(lprRulTabDTOList);
            packageCounter = ruleListMap.size();
            log.info("{}:阶段:规则按包分组 耗时:{}", bn, stopWatch.getTime());
            stopWatch.reset();
            stopWatch.start();

            //to disk
            String droolsDirectory = kbsLoadPackageRuleManager.toDisk(ruleListMap);
            log.info("{}:阶段:写入drl文件 目录:{} 耗时:{}", bn, droolsDirectory, stopWatch.getTime());
            List<File> drlFileList = FileUtil.listFilesBySuffix(droolsDirectory, FileSuffixEnum.DRL);
            if (CollectionUtils.isEmpty(drlFileList)) {
                return;
            }
            log.info("{}:阶段:读取drl文件 目录:{} drl文件数:{} 耗时:{}", bn, droolsDirectory, drlFileList.size(), stopWatch.getTime());
            stopWatch.reset();
            stopWatch.start();
            List<FileSystemResource> fileSystemResourceList = drlFileList.stream().map(a -> new FileSystemResource(a)).collect(Collectors.toList());
            KnowledgeBuilder knowledgeBuilder0010 = KnowledgeBuilderFactory.newKnowledgeBuilder();
            CompositeKnowledgeBuilder compositeKnowledgeBuilder0010 = knowledgeBuilder0010.batch();
            compositeKnowledgeBuilder0010.type(ResourceType.DRL);
            fileSystemResourceList.stream().forEach(a -> {
                compositeKnowledgeBuilder0010.add(a);
            });
            log.info("{}:阶段:CompositeKnowledgeBuilder.add 耗时:{}", bn, stopWatch.getTime());
            stopWatch.reset();
            stopWatch.start();
            log.info("{}:阶段:CompositeKnowledgeBuilder.build begin", bn);
            compositeKnowledgeBuilder0010.build();
            log.info("{}:阶段:CompositeKnowledgeBuilder.build 耗时:{}", bn, stopWatch.getTime());
            KnowledgeBuilderErrors knowledgeBuilderErrors = knowledgeBuilder0010.getErrors();
            if (CollectionUtils.isNotEmpty(knowledgeBuilderErrors)) {
                knowledgeBuilderErrors.iterator().forEachRemaining((x) -> {
                    String errorMessage = String.format("line [ %s ] - %s", JSON.toJSONString(x.getLines()), x.getMessage());
                    log.error("{}:阶段:CompositeKnowledgeBuilder.build 编译报错 耗时:{}", bn, errorMessage);

                });
                AssertUtil.isTrue(Boolean.FALSE, BizErrorCode.START_ERROR, "drl compile error");
                return;
            }
            stopWatch.reset();
            stopWatch.start();
            tempMap.getKIEBASE().addPackages(knowledgeBuilder0010.getKnowledgePackages());
            log.info("{}:阶段:kbs.addPackages 耗时:{}", bn, stopWatch.getTime());

            //4.替换map
            ruleKieBaseTool = tempMap;

        } catch (Throwable e) {
            result = Boolean.FALSE;
            log.error("{}:阶段:策略规则加载结束 系统异常:异常文本:{} 异常类型:{} 异常栈:", bn, e.getMessage(), e.getClass().getName(), e);
            throw e;
        } finally {
            log.info("{}:阶段:策略规则加载结束 result:{} 耗时:{} 组数:{} 每组包数:{} 包数:{} ", bn, result, stopWatchForAll.getTime(), groupNumberCounter, PACKAGE_SIZE_ONE_GROUP, packageCounter);
            //async access kbs
            //kbsLoadPackageRuleManager.asyncAccessKbs(ruleKieBaseTool.getKIEBASE());
        }

    }

    //end+++++++++++++++++++++++++

4 I do not understand  "rewriting the rules in pure Java at compile time",Can you give me a demo? for  /tmp/2024022219/rule_603_1_0_0_0.drl file

**Comment by repeatthink123yuchao** [comment]
> That's cool because this is probably one of the biggest rules based installation of which I have ever heard. Regarding your question I have a few suggestions:
> 
> 1. Are you using the executable model, i.e. rewriting the rules in pure Java at compile time? If not I strongly suggest to do so: it will make the compilation time a little longer but will pay back with a much faster startup at runtime.
> 2. Do all those rules actually belong to the knowledge base? Isn't it possible to shard them, based on the business logic of your application, and then split them in multiple KieBases, each with a more confined and better defined business scope?
> 3. If you have so many rules I bet that they are automatically generated in some way? If so can you please provide an example of those rules? Maybe we could find some common pattern allowing us to rewrite those rules in a more compact way and reduce their cardinality.


Thank you very much for your reply. The details of the situation are as follows:

1 The current application only has 1 InternalKnowledgeBase
2. The system starts up and loads the drl file in the database. The database is read and the row records are written to the disk drl file. The contents of the file are as follows

directory /tmp/2024022219/rule_603_1_0_0_0.drl

package rule_603_1_0_0;
import java.util.*;
import static xxx.RuleUtils.*;

rule "rule_RD00000214"
    no-loop true
    lock-on-active true
    salience 11
    agenda-group "rule_603_1_0_0"
when
	$map : Map( RuleUtils.ruleEquals(rule_package_name,"rule_603_1_0_0"),equalsString(isExistListInRedis($map,"BLACK","[Org_no=documentNumber,P_subscribeLabel=subscribeLabel]&[License=documentNumber,P_subscribeLabel=subscribeLabel]"),"Y")
 	)

then
	 RuleUtils.assembleHitRuleCodes($map,"RD00000214");
	 RuleUtils.put($map,"RSE00000083_RGC00007454_setresult","pass");
RuleUtils.put($map,"M_ID_matched_flag","Y");

end


3 The project startup code is like this

    /**
     * Initialize rule component group
     */
    @PostConstruct
    public void concurrencyLoadInit() {
        String bn = "concurrency:policy rule initialization";
        Boolean result = Boolean.TRUE;
        StopWatch stopWatchForAll = StopWatch.createStarted();
        //group counter
        Integer groupNumberCounter = 0;
        //package counter
        Integer packageCounter = 0;
        //rule counter
        try {
            logger.info("{}:阶段:begin", bn);
            RuleKieBaseTool tempMap = new RuleKieBaseTool();
            StopWatch stopWatch = StopWatch.createStarted();
            //2.读取rule表配置信息 策略发布状态成功 + 规则组件状态上线成功 +规则已发布
            List<LprRulTabDTO> lprRulTabDTOList = rulTabMapper.selectByStatus(RuleEnum.RULE_RELEASE_SUCCESS.getCode());
            log.info("{}:阶段:策略规则初始化获取规则数据库配置完成 行记录数:{} 耗时:{}", bn, lprRulTabDTOList.size(), stopWatch.getTime());
            stopWatch.reset();
            stopWatch.start();

            //Map<package,List<rule>>
            Map<String, List<String>> ruleListMap = decodeRuleSetByTab(lprRulTabDTOList);
            packageCounter = ruleListMap.size();
            log.info("{}:阶段:规则按包分组 耗时:{}", bn, stopWatch.getTime());
            stopWatch.reset();
            stopWatch.start();

            //to disk
            String droolsDirectory = kbsLoadPackageRuleManager.toDisk(ruleListMap);
            log.info("{}:阶段:写入drl文件 目录:{} 耗时:{}", bn, droolsDirectory, stopWatch.getTime());
            List<File> drlFileList = FileUtil.listFilesBySuffix(droolsDirectory, FileSuffixEnum.DRL);
            if (CollectionUtils.isEmpty(drlFileList)) {
                return;
            }
            log.info("{}:阶段:读取drl文件 目录:{} drl文件数:{} 耗时:{}", bn, droolsDirectory, drlFileList.size(), stopWatch.getTime());
            stopWatch.reset();
            stopWatch.start();
            List<FileSystemResource> fileSystemResourceList = drlFileList.stream().map(a -> new FileSystemResource(a)).collect(Collectors.toList());
            KnowledgeBuilder knowledgeBuilder0010 = KnowledgeBuilderFactory.newKnowledgeBuilder();
            CompositeKnowledgeBuilder compositeKnowledgeBuilder0010 = knowledgeBuilder0010.batch();
            compositeKnowledgeBuilder0010.type(ResourceType.DRL);
            fileSystemResourceList.stream().forEach(a -> {
                compositeKnowledgeBuilder0010.add(a);
            });
            log.info("{}:阶段:CompositeKnowledgeBuilder.add 耗时:{}", bn, stopWatch.getTime());
            stopWatch.reset();
            stopWatch.start();
            log.info("{}:阶段:CompositeKnowledgeBuilder.build begin", bn);
            compositeKnowledgeBuilder0010.build();
            log.info("{}:阶段:CompositeKnowledgeBuilder.build 耗时:{}", bn, stopWatch.getTime());
            KnowledgeBuilderErrors knowledgeBuilderErrors = knowledgeBuilder0010.getErrors();
            if (CollectionUtils.isNotEmpty(knowledgeBuilderErrors)) {
                knowledgeBuilderErrors.iterator().forEachRemaining((x) -> {
                    String errorMessage = String.format("line [ %s ] - %s", JSON.toJSONString(x.getLines()), x.getMessage());
                    log.error("{}:阶段:CompositeKnowledgeBuilder.build 编译报错 耗时:{}", bn, errorMessage);

                });
                AssertUtil.isTrue(Boolean.FALSE, BizErrorCode.START_ERROR, "drl compile error");
                return;
            }
            stopWatch.reset();
            stopWatch.start();
            tempMap.getKIEBASE().addPackages(knowledgeBuilder0010.getKnowledgePackages());
            log.info("{}:阶段:kbs.addPackages 耗时:{}", bn, stopWatch.getTime());

            //4.替换map
            ruleKieBaseTool = tempMap;

        } catch (Throwable e) {
            result = Boolean.FALSE;
            log.error("{}:阶段:策略规则加载结束 系统异常:异常文本:{} 异常类型:{} 异常栈:", bn, e.getMessage(), e.getClass().getName(), e);
            throw e;
        } finally {
            log.info("{}:阶段:策略规则加载结束 result:{} 耗时:{} 组数:{} 每组包数:{} 包数:{} ", bn, result, stopWatchForAll.getTime(), groupNumberCounter, PACKAGE_SIZE_ONE_GROUP, packageCounter);
            //async access kbs
            //kbsLoadPackageRuleManager.asyncAccessKbs(ruleKieBaseTool.getKIEBASE());
        }

    }

    //end+++++++++++++++++++++++++

4 I do not understand  "rewriting the rules in pure Java at compile time",Can you give me a demo? for  /tmp/2024022219/rule_603_1_0_0_0.drl file

**Comment by mariofusco** [comment]
Regarding my suggestion 3. I strongly advice to give a look at how the [executable model](https://docs.drools.org/7.74.1.Final/drools-docs/html_single/index.html#executable-model-con_packaging-deploying) works. In essence if you precompile the rules with it instead of doing this from scratch at when the rules are loaded will improve your startup time between 10 and 100 times. Also if possible would be beneficial to try to split your single monolithic knowledge base in smaller ones.

**Comment by repeatthink123yuchao** [comment]
> Regarding my suggestion 3. I strongly advice to give a look at how the [executable model](https://docs.drools.org/7.74.1.Final/drools-docs/html_single/index.html#executable-model-con_packaging-deploying) works. In essence if you precompile the rules with it instead of doing this from scratch at when the rules are loaded will improve your startup time between 10 and 100 times. Also if possible would be beneficial to try to split your single monolithic knowledge base in smaller ones.



#############
drools source code
#############
#
org.kie.internal.builder.CompositeKnowledgeBuilder#add(org.kie.api.io.Resource)
org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl#build
----org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl#getResources
----|->一个包对应一个 Resource , 封成 List<Resource>
----|->[fast]
----org.drools.compiler.builder.impl.KnowledgeBuilderImpl#buildResources
----|->List<Resource> 添加到 Stack<List<Resource>> 
----|->[fast]
----org.drools.compiler.builder.impl.KnowledgeBuilderImpl#buildPackages
--------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#initPackageRegistries
--------|->Collection<CompositePackageDescr> 包描述转包注册 Map<String, PackageRegistry>
--------|->[fast]
--------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#normalizeTypeAnnotations
--------|->[fast]
--------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#buildTypeDeclarations
--------|->构建类型声明
--------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#buildEntryPoints
--------|->[fast]
--------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#buildOtherDeclarations
--------|->[fast]
--------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#normalizeRuleAnnotations
--------|->[fast]
--------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#buildRules
--------|->[slow]
--------|->Slow Cause Analysis
------------1:遍历包/遍历每个包中规则,将drl文件转class并注册到 invoker
------------2:
------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#compileKnowledgePackages
----------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#validateUniqueRuleNames
----------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#compileFunctions
----------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#compileRules
--------------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#compileRules
------------------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#preProcessRules
------------------------|->清理此包的存量规则,为下一步做准备
------------------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#sortRulesByDependency
------------------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#compileAllQueries
------------------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#compileRulesLevel
------------------------|-> 一个包中的规则数大于 parallelRulesBuildThreshold 时会 new ForkJoinPool() 并发编译
----------------------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#initRuleDescr
----------------------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#buildRuleBuilderContext
----------------------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#addRule
--------------------------------org.drools.compiler.rule.builder.RuleBuilder#build
--------------------------------org.drools.compiler.rule.builder.RuleBuilder#buildAttributes
--------------------------------org.drools.compiler.rule.builder.dialect.asm.AbstractASMConsequenceBuilder#build
--------------------------------|->drl 生成 class code 并注册到 invoker 
------------------------------------org.drools.compiler.rule.builder.dialect.java.JavaRuleBuilderHelper#registerInvokerBytecode
------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#wireAllRules
----------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#compileAll
--------------------org.drools.compiler.compiler.PackageRegistry#compileAll
------------------------org.drools.compiler.compiler.DialectCompiletimeRegistry#compileAll
----------------------------org.drools.compiler.rule.builder.dialect.java.JavaDialect#compileAll
--------------------------------org.drools.compiler.rule.builder.dialect.java.JavaDialect#dumpResources
--------------------------------|->class对应的java写出到目录
--------------------------------|->org.drools.compiler.commons.jci.readers.MemoryResourceReader#resources 这个字段map型,key即规则名,value即规则的java文件
--------------------------------org.drools.compiler.commons.jci.compilers.JavaCompiler#compile(java.lang.String[], org.drools.compiler.commons.jci.readers.ResourceReader, org.drools.compiler.commons.jci.stores.ResourceStore, java.lang.ClassLoader)
------------------------------------org.drools.compiler.commons.jci.compilers.EclipseJavaCompiler#compile
------------------------------------|->
------------------------------------org.eclipse.jdt.internal.compiler.Compiler#compile(org.eclipse.jdt.internal.compiler.env.ICompilationUnit[], boolean)
------------------------------------
----------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#reloadAll
----------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#updateResults()
------------org.drools.compiler.builder.impl.KnowledgeBuilderImpl#processKieBaseTypes
------------
------------
--------------------------------
----org.drools.compiler.builder.impl.KnowledgeBuilderImpl#buildProcesses
----org.drools.compiler.builder.impl.KnowledgeBuilderImpl#buildOthers
----


#############
Our solution
#############
1 Split 80000 packages into 4 kie
2 At startup, each knowledge base is compiled by a single thread
3 Finally, start the thread to assemble the mapping between the package and the knowledge base

**Comment by repeatthink123yuchao** [comment]
> Regarding my suggestion 3. I strongly advice to give a look at how the [executable model](https://docs.drools.org/7.74.1.Final/drools-docs/html_single/index.html#executable-model-con_packaging-deploying) works. In essence if you precompile the rules with it instead of doing this from scratch at when the rules are loaded will improve your startup time between 10 and 100 times. Also if possible would be beneficial to try to split your single monolithic knowledge base in smaller ones.

Okay, thank you very much. I will carefully review the official documentation and source code. Thank you again
