### ISSUE TITLE
[new-parser] `PackageDescr.resource` not set

### ISSUE THREAD

**Issue by yurloc** [apache/incubator-kie#5933]
## Parent issue
- #5678 

## Failing tests
- `org.drools.mvel.compiler.compiler.DescrResourceSetTest#drlFilesTest`

## Notes
`DRLVisitorImpl` should simply set the `Resource` that was parsed to each `Descr` in the resulting AST.

## Rule code snippet
N/A.

## Error output
```
### parse : ANTLR4_PARSER_ENABLED = true

java.lang.AssertionError: [PackageDescr.resource is null!] 
Expecting actual not to be null

	at org.drools.mvel.compiler.compiler.PackageDescrResourceVisitor.checkResource(PackageDescrResourceVisitor.java:76)
	at org.drools.mvel.compiler.compiler.PackageDescrResourceVisitor.visit(PackageDescrResourceVisitor.java:315)
	at org.drools.mvel.compiler.compiler.DescrResourceSetTest.drlFilesTest(DescrResourceSetTest.java:63)
```

**Comment by yurloc** [comment]
`good-first-issue`

**Comment by tkobayas** [comment]
`/take` This seems to be a little more complex than the first look.

**Comment by tkobayas** [comment]
`DescrResourceSetTest` goes through all drl files in `test-compiler-integration`. If there is a parser error, the resource assertion is skipped. So it's better to hold on this fix until some other test failures will be fixed.

**Comment by tkobayas** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/pull/5984
