### ISSUE TITLE
Getting compilation error while running the command "mvn test"

### ISSUE THREAD

**Issue by imtavish04** [apache/incubator-kie#5992]
Hi team, 

I am trying to run the UT for the package - org.drools:drools-mvel:8.44.0.Final with JAVA VERSION 11.0.20

however it is showing me the error -> "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project drools-decisiontables: Compilation failure
[ERROR] /root/incubator-kie-drools/drools-decisiontables/src/test/java/org/drools/decisiontable/UnicodeInXLSTest.java:[89,19] error while writing org.drools.decisiontable.UnicodeInXLSTest.?lov?k: bad filename RelativeFile[org/drools/decisiontable/UnicodeInXLSTest$?lov?k.class]
"

Please let me know the solution for the same. 

Thanks

**Comment by tkobayas** [comment]
Probably your env variable `LANG` is not UTF-8? Please try `export LANG=en_US.UTF-8`.

**Comment by tkobayas** [comment]
Closing as no response. Please reopen if needed.
