### ISSUE TITLE
Documentation: Add the previously deleted section on "Advanced rule actions with conditional and named consequences" to current documentation

### ISSUE THREAD

**Issue by JaredDavis22** [apache/incubator-kie#6036]
Would it be acceptable to add this section back to the main documentation?

Why was it removed?

https://docs.drools.org/7.44.0.Final/drools-docs/html_single/#:~:text=4.1.9.3.%20Advanced%20rule%20actions%20with%20conditional%20and%20named%20consequences

(I am willing todo a PR, just want to make sure adding it back is acceptable)

**Comment by JaredDavis22** [comment]
another? version of the same section: 

https://docs.drools.org/7.74.1.Final/drools-docs/html_single/index.html#drl-rules-THEN-advanced-con_drl-rules

**Comment by tkobayas** [comment]
@JaredDavis22 Thank you for raising this issue.

In the next version docs, `Advanced rule actions with conditional and named consequences` section will be back.

If you build the current main branch,
```
cd drools-docs
mvn clean install
```
Open `./target/website/docs/index.html` with a browser. You will find `Rule Language Reference (Traditional)` chapter and `Advanced rule actions with conditional and named consequences` section in it.

**Comment by tkobayas** [comment]
For RuleUnit, it seems to work, but need to add unit tests and documentation in `Rule Language Reference` chapter. Filed https://github.com/apache/incubator-kie-drools/issues/6038

**Comment by tkobayas** [comment]
> In the next version docs, Advanced rule actions with conditional and named consequences section will be back.

When the next version docs will be published, I'll close this issue.
