### ISSUE TITLE
What IDE or Editor for DRL Files?

### ISSUE THREAD

**Issue by piacenti** [apache/incubator-kie#6051]
I looked over all the documentation for the preferred editor for DRL files and apparently Eclipse was best for version 6 and before, Business Center for 7 and apparently nothing for 8 and 9. There was a blog post from 2022 about adding support in VS code but the kogito extension seems to still be missing any DRL support. IntelliJ has a less than ideal support with a lot of issues on rather simple usage, specially when using OOPath. I can see there is a lot of work around the new parser based on ANTLR 4 which I assume is taking the attention and may impact the answer to this but I wanted to ask either way to make sure.

What is the best IDE/editor for versions 8 and 9 of the engine?

**Comment by tkobayas** [comment]
For questions, please use google group (https://groups.google.com/g/drools-usage , https://groups.google.com/g/drools-setup) and zulip chat (https://kie.zulipchat.com/#narrow/stream/232677-drools).

Regarding IDE, indeed we don't have a preferred editor for DRL at the moment. Once Drools 10 is released and the new parser code is merged, we would vitalize the DRL editor development.
