### ISSUE TITLE
Performance issue with many kbase models and many large spreadsheets

### ISSUE THREAD

**Issue by tkobayas** [apache/incubator-kie#6088]
When a KieProject has many kbase models and many large spreadsheets, `buildAll()` becomes slow.

**Comment by tkobayas** [comment]
`AbstractKieProject.buildKnowledgePackages` is called per kbase model. 
`KieBuilderImpl.filterFileInKBase` is called per file.

Then, `KieBuilderImpl.packageNameFromDtable` -> `DecisionTableProviderImpl.loadFromResource` -> `SpreadsheetCompiler.compile` is called.

If a KieProject has 20 kbase models and 20 spreadsheets, `packageNameFromDtable` is called 400 times. One `packageNameFromDtable`  may not take very long time (1 or 2 seconds), but 400 times are significant.

**Comment by mariofusco** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/commit/011e17a70e74988e4c75a83e208faf912ec147ac
