### ISSUE TITLE
flaky test: org.drools.compiler.integrationtests.TimerAndCalendarFireUntilHaltTest

### ISSUE THREAD

**Issue by tkobayas** [apache/incubator-kie#6093]
probably more likely to occur in Windows, but saw in ubuntu-latest, too.

**Comment by Anju023** [comment]
download//bit.ly/3XQLHlHI put the necessary dlls in the archive

**Comment by tkobayas** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/pull/6096
