### ISSUE TITLE
Evaluation Agenda Filter for RuleUnit

### ISSUE THREAD

**Issue by piacenti** [apache/incubator-kie#6173]
While trying to add filters for which rules to run during execution of a rule unit, I found that the agenda filters provided are only used to prevent the rule to fire/execute action, not it's evaluation. We have thousands of rules including some that can be computationally intensive, however, most of the time we need to filter them anyways so, the lack of an evaluation filter can be a bit of a problem for performance at times.

**Comment by mariofusco** [comment]
Due to node sharing and the need of propagating all facts in the evaluation network, it is not possible to prevent the evaluation of the inserted facts. The laziness of the phreak algorithm should however largely mitigate the problem.
